### ISSUE TITLE
 type is not available in this platform

### ISSUE THREAD

**Issue by wimdeblauwe** [gluonhq/client-samples#10]
I am trying to add the Gluon client plugin to the sample from openjfx, but running `mvn client:compile` gives the following exception:

```
SUB] [hellofx:42070]     analysis:  15,648.12 ms
[SUB] Warning: Aborting stand-alone image build. Unsupported features in 2 methods
[SUB] Detailed message:
[SUB] Error: type is not available in this platform: com.oracle.svm.hosted.c.CGlobalDataFeature
[SUB] Trace:    object java.lang.Class[]
[SUB]   object java.lang.invoke.MethodType
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node[]
[SUB]   object java.util.concurrent.ConcurrentHashMap
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet
[SUB]   method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
[SUB] Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.methodType(MethodType.java:212)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandleReferences$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleReferences.java:59)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
[SUB]   at java.base@12.0.1/java.lang.String.valueOf(String.java:3042)
[SUB]   at java.base@12.0.1/java.io.PrintStream.print(PrintStream.java:745)
[SUB]   at java.base@12.0.1/java.io.PrintStream.println(PrintStream.java:882)
[SUB]   at app//com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
[SUB]   at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
[SUB] Error: type is not available in this platform: com.oracle.svm.hosted.code.CFunctionCallStubMethod
[SUB] Trace:    object java.lang.invoke.MethodType
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node[]
[SUB]   object java.util.concurrent.ConcurrentHashMap
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet
[SUB]   method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
[SUB] Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.methodType(MethodType.java:212)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandleReferences$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleReferences.java:59)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
[SUB]   at java.base@12.0.1/java.lang.String.valueOf(String.java:3042)
[SUB]   at java.base@12.0.1/java.io.PrintStream.print(PrintStream.java:745)
[SUB]   at java.base@12.0.1/java.io.PrintStream.println(PrintStream.java:882)
[SUB]   at app//com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
[SUB]   at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
[SUB] 
[SUB] com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Aborting stand-alone image build. Unsupported features in 2 methods
[SUB] Detailed message:
[SUB] Error: type is not available in this platform: com.oracle.svm.hosted.c.CGlobalDataFeature
[SUB] Trace:    object java.lang.Class[]
[SUB]   object java.lang.invoke.MethodType
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node[]
[SUB]   object java.util.concurrent.ConcurrentHashMap
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet
[SUB]   method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
[SUB] Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.methodType(MethodType.java:212)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandleReferences$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleReferences.java:59)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
[SUB]   at java.base@12.0.1/java.lang.String.valueOf(String.java:3042)
[SUB]   at java.base@12.0.1/java.io.PrintStream.print(PrintStream.java:745)
[SUB]   at java.base@12.0.1/java.io.PrintStream.println(PrintStream.java:882)
[SUB]   at app//com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
[SUB]   at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
[SUB] Error: type is not available in this platform: com.oracle.svm.hosted.code.CFunctionCallStubMethod
[SUB] Trace:    object java.lang.invoke.MethodType
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node[]
[SUB]   object java.util.concurrent.ConcurrentHashMap
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet
[SUB]   method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
[SUB] Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.methodType(MethodType.java:212)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandleReferences$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleReferences.java:59)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
[SUB]   at java.base@12.0.1/java.lang.String.valueOf(String.java:3042)
[SUB]   at java.base@12.0.1/java.io.PrintStream.print(PrintStream.java:745)
[SUB]   at java.base@12.0.1/java.io.PrintStream.println(PrintStream.java:882)
[SUB]   at app//com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
[SUB]   at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
[SUB] 
[SUB]   at com.oracle.svm.hosted.FallbackFeature.reportFallback(FallbackFeature.java:208)
[SUB]   at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:218)
[SUB]   at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:732)
[SUB]   at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:522)
[SUB]   at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
[SUB]   at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1406)
[SUB]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[SUB]   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[SUB]   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[SUB]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[SUB]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[SUB] Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
[SUB] Detailed message:
[SUB] Error: type is not available in this platform: com.oracle.svm.hosted.c.CGlobalDataFeature
[SUB] Trace:    object java.lang.Class[]
[SUB]   object java.lang.invoke.MethodType
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node[]
[SUB]   object java.util.concurrent.ConcurrentHashMap
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet
[SUB]   method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
[SUB] Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.methodType(MethodType.java:212)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandleReferences$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleReferences.java:59)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
[SUB]   at java.base@12.0.1/java.lang.String.valueOf(String.java:3042)
[SUB]   at java.base@12.0.1/java.io.PrintStream.print(PrintStream.java:745)
[SUB]   at java.base@12.0.1/java.io.PrintStream.println(PrintStream.java:882)
[SUB]   at app//com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
[SUB]   at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
[SUB] Error: type is not available in this platform: com.oracle.svm.hosted.code.CFunctionCallStubMethod
[SUB] Trace:    object java.lang.invoke.MethodType
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node
[SUB]   object java.util.concurrent.ConcurrentHashMap$Node[]
[SUB]   object java.util.concurrent.ConcurrentHashMap
[SUB]   object java.lang.invoke.MethodType$ConcurrentWeakInternSet
[SUB]   method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
[SUB] Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
[SUB]   at java.base@12.0.1/java.lang.invoke.MethodType.methodType(MethodType.java:212)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle$AccessType.accessModeType(VarHandle.java:1569)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandleReferences$FieldInstanceReadOnly.accessModeTypeUncached(VarHandleReferences.java:59)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.accessModeType(VarHandle.java:1919)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.varType(VarHandle.java:1886)
[SUB]   at java.base@12.0.1/java.lang.invoke.VarHandle.toString(VarHandle.java:1876)
[SUB]   at java.base@12.0.1/java.lang.String.valueOf(String.java:3042)
[SUB]   at java.base@12.0.1/java.io.PrintStream.print(PrintStream.java:745)
[SUB]   at java.base@12.0.1/java.io.PrintStream.println(PrintStream.java:882)
[SUB]   at app//com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
[SUB]   at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
[SUB] 
[SUB]   at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:133)
[SUB]   at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
[SUB]   at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:683)
[SUB]   ... 8 more
java.lang.RuntimeException: Error compiling
        at com.gluonhq.omega.SVMBridge.compile(SVMBridge.java:306)
        at com.gluonhq.omega.target.MacosTargetConfiguration.compileApplication(MacosTargetConfiguration.java:411)
        at com.gluonhq.omega.target.AbstractTargetConfiguration.compile(AbstractTargetConfiguration.java:311)
        at com.gluonhq.omega.Omega.nativeCompile(Omega.java:91)
        at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:73)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.072 s
[INFO] Finished at: 2019-06-18T14:59:15+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.0.9:compile (default-cli) on project hellofx: Error: Error compiling -> [Help 1]
[ERROR] 
```

I have attached a zip file with the source code I am using.
[hellofx-sample.zip](https://github.com/gluonhq/client-samples/files/3301572/hellofx-sample.zip)

This is the gluon client plugin config in Maven I am using:

```
            <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>client-maven-plugin</artifactId>
                <version>0.0.9</version>
                <configuration>
                    <!-- Uncomment to run on iOS: -->
                    <!-- <target>ios</target>-->
                    <mainClass>${mainClassName}</mainClass>
                    <bundlesList>
                    </bundlesList>
                    <reflectionList>
                        <list>javafx.fxml.FXMLLoader</list>
                        <list>org.openjfx.PrimaryController</list>
                        <list>org.openjfx.SecondaryController</list>
                        <list>javafx.scene.control.Button</list>
                        <list>javafx.scene.control.Label</list>
                        <list>javafx.scene.layout.VBox</list>
                        <list>javafx.geometry.Insets</list>
                    </reflectionList>
                </configuration>
            </plugin>
```

**Comment by jperedadnr** [comment]
Java 12 is not supported yet. You need Java 11. JavaFX can be 11 or 12. Can you try again?

**Comment by wimdeblauwe** [comment]
My apologies, I forget I changed that to 12. After changing it back to 11 it works.

I did get this exception at first:
```
java.lang.IllegalArgumentException: Unable to coerce CENTER to class javafx.geometry.Pos.
```

But adding this to the `reflectionList` of the plugin fixed it:
```
<list>javafx.geometry.Pos</list>
```

So all classes used in FXML files will need to be added in that list I guess?

**Comment by jperedadnr** [comment]
Yes, all the JavaFX "classes" that you add to an FXML file are then invoked via reflection. While the default list of classes includes most of the usual classes, you can still need extra ones, like the one you have mentioned.
