### ISSUE TITLE
HelloFX startup crash on Android. Plugin version 0.1.30

### ISSUE THREAD

**Issue by AlmasB** [gluonhq/client-samples#103]
```
OS: Ubuntu 16.04. 
graalvm: tested with both `GraalVM CE 20.3.0-dev-20200730_0206` and `GraalVM CE 20.3.0-dev-20200807_0204` (latest when creating the issue)
android sdk/ndk: downloaded automatically by the plugin
Android: 8.0
```

```
mvn client:run
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.30:run (default-cli) @ hellofx ---
[Sun Aug 09 09:12:47 BST 2020][INFO] ==================== RUN TASK ====================
[Sun Aug 09 09:12:47 BST 2020][INFO] [SUB] --------- beginning of main
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] --------- beginning of system
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/ActivityManager( 3651): getPackageFromAppProcesses, return null :14990
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] V/GraalActivity(15003): onCreate start, using Android Logging v1
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] V/GraalActivity(15003): onCreate done
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] V/GraalActivity(15003): onStart
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] V/GraalActivity(15003): onStart done
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] V/GraalActivity(15003): onResume
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] V/GraalActivity(15003): onResume done
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] V/GraalActivity(15003): surfaceCreated for com.gluonhq.helloandroid.MainActivity@b2f04f8
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] V/GraalActivity(15003): loading substrate library
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] --------- beginning of crash
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): FATAL EXCEPTION: main
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): Process: hello.hellofx, PID: 15003
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__svm_vm_is_static_binary" referenced by "/data/app/hello.hellofx-NwuxSS0P1B0K6uh5pswjKg==/lib/arm64/libsubstrate.so"...
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at java.lang.System.loadLibrary(System.java:1657)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.SurfaceView.updateSurface(SurfaceView.java:753)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:154)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1045)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2808)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.Choreographer.doFrame(Choreographer.java:658)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.os.Handler.handleCallback(Handler.java:789)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.os.Handler.dispatchMessage(Handler.java:98)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.os.Looper.loop(Looper.java:164)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at java.lang.reflect.Method.invoke(Native Method)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] E/AndroidRuntime(15003): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] W/ActivityManager( 3651): crash : hello.hellofx,0
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] W/ActivityManager( 3651):   Force finishing activity hello.hellofx/com.gluonhq.helloandroid.MainActivity
[Sun Aug 09 09:12:48 BST 2020][INFO] [SUB] W/ActivityManager( 3651): Activity pause timeout for ActivityRecord{fe9378e u0 hello.hellofx/com.gluonhq.helloandroid.MainActivity t4 f}
[Sun Aug 09 09:12:59 BST 2020][INFO] [SUB] W/ActivityManager( 3651): Activity destroy timeout for ActivityRecord{fe9378e u0 hello.hellofx/com.gluonhq.helloandroid.MainActivity t4 f}
[Sun Aug 09 09:13:00 BST 2020][INFO] [SUB] W/ActivityManager( 3651): setHasOverlayUi called on unknown pid: 15003
```

**Comment by jperedadnr** [comment]
Should be fixed with https://github.com/gluonhq/substrate/pull/738
(for now it can be tested with Client 0.1.31-SNAPSHOT)
