### ISSUE TITLE
[Enviroment] GraalVM installation directory not found

### ISSUE THREAD

**Issue by chihung93** [gluonhq/client-samples#113]
I can not run project to export APK/IPA for Android/iOS. Please help me to figure out this problem.
Thanks.

```
"/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home/bin/java" -Dmaven.multiModuleProjectDirectory=/Users/henry/Downloads/client-samples-master/Maven/HelloWorld "-Dmaven.home=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" "-Dmaven.ext.class.path=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven-event-listener.jar" "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=64882:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar" org.codehaus.classworlds.Launcher -Didea.version2019.3.5 com.gluonhq:client-maven-plugin:0.1.31:package
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.31:package (default-cli) @ helloworld ---
org.apache.maven.plugin.MojoExecutionException: GraalVM installation directory not found. Either set GRAALVM_HOME as an environment variable or set graalvmHome in client-plugin configuration
	at com.gluonhq.NativeBaseMojo.createSubstrateDispatcher(NativeBaseMojo.java:131)
	at com.gluonhq.NativePackageMojo.execute(NativePackageMojo.java:47)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.958 s
[INFO] Finished at: 2020-08-30T15:03:57+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.31:package (default-cli) on project helloworld: Error: GraalVM installation directory not found. Either set GRAALVM_HOME as an environment variable or set graalvmHome in client-plugin configuration -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

<img width="821" alt="Screen Shot 2020-08-30 at 15 04 37" src="https://user-images.githubusercontent.com/5199109/91654370-577c0a00-ead2-11ea-8236-b00f872ff369.png">
<img width="857" alt="Screen Shot 2020-08-30 at 15 04 42" src="https://user-images.githubusercontent.com/5199109/91654375-5ba82780-ead2-11ea-846c-443a736425d4.png">
<img width="858" alt="Screen Shot 2020-08-30 at 15 04 49" src="https://user-images.githubusercontent.com/5199109/91654378-5c40be00-ead2-11ea-9d28-785943101a76.png">
<img width="703" alt="Screen Shot 2020-08-30 at 15 04 59" src="https://user-images.githubusercontent.com/5199109/91654379-5d71eb00-ead2-11ea-99ad-1b2d016e7f2c.png">
<img width="847" alt="Screen Shot 2020-08-30 at 15 05 28" src="https://user-images.githubusercontent.com/5199109/91654380-5e0a8180-ead2-11ea-9bb0-857d55485234.png">
<img width="478" alt="Screen Shot 2020-08-30 at 15 05 39" src="https://user-images.githubusercontent.com/5199109/91654382-5f3bae80-ead2-11ea-887e-e3d26119cfb4.png">

**Comment by jperedadnr** [comment]
Are you running your project directly from IntelliJ's Maven window? If that is the case, `GRAALVM_HOME` might not be defined, and you get the error:

> GraalVM installation directory not found. Either set GRAALVM_HOME as an environment variable or set graalvmHome in client-plugin configuration

that explains how to solve it:

```
<configuration>
    <target>iOS</target>
    <graalvmHome>/path/to/your/GraalVMHome</graalvmHome>
    <mainClass>hello.HelloWorld</mainClass>
</configuration>
```

Alternatively, you can add the environment variable to IntelliJ.

And finally, you can also go to the Terminal view in IntelliJ, and run `mvn client:package`, as the environment variable is defined.


Either way, I see you are running `client:package`, but did you run first `client:build`?

**Comment by chihung93** [comment]
@jperedadnr :
 I see you are running client:package, but did you run first client:build => Yes, I have run client: clean +build before package

Do you know how to resolve that ?


```


/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/henry/Downloads/client-samples-master/Maven/HelloWorld "-Dmaven.home=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" "-Dmaven.ext.class.path=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven-event-listener.jar" "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=61782:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar" org.codehaus.classworlds.Launcher -Didea.version2019.3.5 com.gluonhq:client-maven-plugin:0.1.31:build
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.31:build (default-cli) @ helloworld ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.315 s
[INFO] Finished at: 2020-09-02T23:40:22+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.31:build (default-cli) on project helloworld: Error, client:build failed: Error while executing process. Cannot run program "/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/bin/mvn" (in directory "/Users/henry/Downloads/client-samples-master/Maven/HelloWorld"): error=13, Permission denied -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```




I have tried this one but not work for resolving this issue above?

**sudo**` /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/henry/Downloads/client-samples-master/Maven/HelloWorld "-Dmaven.home=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" "-Dmaven.ext.class.path=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven-event-listener.jar" "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=61782:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar" org.codehaus.classworlds.Launcher -Didea.version2019.3.5 com.gluonhq:client-maven-plugin:0.1.31:build`
