### ISSUE TITLE
Can't run examples using recommended graalvm-ce-java11-20.2.0 -- seems graalvm-ce-java11-20.1.0 is required (?!)

### ISSUE THREAD

**Issue by woj-tek** [gluonhq/client-samples#115]
Steps to reproduce:
* install graalvm-ce-java11-20.2.0 as per [requirements](https://github.com/gluonhq/client-samples#requirements):
```
$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
```
* clone repository and navigate to one of the examples (gluonhq-client-samples/Maven/HelloFXML)
* try to build as per [instructions](https://github.com/gluonhq/client-samples#build-using-maven):
```
$ mvn clean client:build
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< hello:hellofxml >---------------------------
[INFO] Building hellofxml 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hellofxml ---
[INFO]
[INFO] --------------------------< hello:hellofxml >---------------------------
[INFO] Building hellofxml 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.31:build (default-cli) @ hellofxml ---
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< hello:hellofxml >---------------------------
[INFO] Building hellofxml 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> client-maven-plugin:0.1.31:compile (default-cli) > process-classes @ hellofxml >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellofxml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellofxml ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/wojtek/dev/_mine/java/gluonhq-client-samples/Maven/HelloFXML/target/classes
[INFO]
[INFO] <<< client-maven-plugin:0.1.31:compile (default-cli) < process-classes @ hellofxml <<<
[INFO]
[INFO]
[INFO] --- client-maven-plugin:0.1.31:compile (default-cli) @ hellofxml ---
sept. 12, 2020 6:44:29 P. M. com.gluonhq.substrate.util.Logger logSevere
SEVERE: Process check xattr failed with result: 1
Check the log files under null
And please check https://docs.gluonhq.com/client/ for more information.
sept. 12, 2020 6:44:29 P. M. com.gluonhq.substrate.util.Logger logInfo
INFO: Logging process [check xattr] to file: /Users/wojtek/dev/_mine/java/gluonhq-client-samples/Maven/HelloFXML/target/client/log/process-check xattr-1599947069679.log
java.io.IOException: Path provided for GraalVM doesn't exist: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
	at com.gluonhq.substrate.model.InternalProjectConfiguration.getGraalVMBinPath(InternalProjectConfiguration.java:509)
	at com.gluonhq.substrate.model.InternalProjectConfiguration.getGraalVersion(InternalProjectConfiguration.java:107)
	at com.gluonhq.substrate.model.InternalProjectConfiguration.checkGraalVMVersion(InternalProjectConfiguration.java:417)
	at com.gluonhq.substrate.SubstrateDispatcher.<init>(SubstrateDispatcher.java:371)
	at com.gluonhq.NativeBaseMojo.createSubstrateDispatcher(NativeBaseMojo.java:136)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:53)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.635 s
[INFO] Finished at: 2020-09-12T18:44:29-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.31:compile (default-cli) on project hellofxml: Error: Path provided for GraalVM doesn't exist: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.972 s
[INFO] Finished at: 2020-09-12T18:44:29-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.31:build (default-cli) on project hellofxml: Error, client:build failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Log file (/Users/wojtek/dev/_mine/java/gluonhq-client-samples/Maven/HelloFXML/target/client/log/process-check xattr-1599947069679.log) doesn't contain anything relevat apart from reiterating older Graal version:
```
Process
=======
check xattr

Command Line
============
xattr /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0

Output
======
xattr: No such file: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0


Result
======
result: 1
```

**Comment by jperedadnr** [comment]
Did you update `GRAALVM_HOME`? Looks like it still points to the previous GraalVM installation.

**Comment by woj-tek** [comment]
Ehh, mea culpa. Maybe adding to the exception "Path provided for GraalVM doesn't exist" explicit information about `GRAALVM_HOME` would be a good idea? easy to miss and would probably help some lost souls :)
