### ISSUE TITLE
Unable to compile examples from IntelliJ IDEA

### ISSUE THREAD

**Issue by wertklop** [gluonhq/client-samples#13]
I am try compile HelloWorld sample, but I get exception:

> /jdk-11/bin/java -Dmaven.multiModuleProjectDirectory=/IdeaProjects/client-samples/Maven/HelloWorld -Dmaven.home=/idea-IC/plugins/maven/lib/maven3 -Dclassworlds.conf=/idea-IC/plugins/maven/lib/maven3/bin/m2.conf -javaagent:/idea-IC/lib/idea_rt.jar=35078:/idea-IC/bin -Dfile.encoding=UTF-8 -classpath /idea-IC/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version2019.1.3 com.gluonhq:client-maven-plugin:0.0.10:compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.0.10:compile (default-cli) @ helloworld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /idea-IC/IdeaProjects/client-samples/Maven/HelloWorld/src/main/resources
[INFO] Nothing to compile - all classes are up to date
Omega :: host triplet = x86_64-linux-linux
Omega :: target triplet = x86_64-linux-linux
java.lang.RuntimeException: Error compiling
	at com.gluonhq.omega.SVMBridge.compile(SVMBridge.java:307)
	at com.gluonhq.omega.target.LinuxTargetProcess.compileApplication(LinuxTargetProcess.java:105)
	at com.gluonhq.omega.target.AbstractTargetProcess.compile(AbstractTargetProcess.java:318)
	at com.gluonhq.omega.Omega.nativeCompile(Omega.java:72)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:73)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.382 s
[INFO] Finished at: 2019-07-02T16:13:08+03:00
[INFO] Final Memory: 13M/47M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.0.10:compile (default-cli) on project helloworld: Error: Error compiling -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] [SUB] Unrecognized VM option 'EnableJVMCI'
[INFO] [SUB] Unrecognized VM option 'EnableJVMCI'
[INFO] [SUB] Error: Could not create the Java Virtual Machine.
Process finished with exit code 1

**Comment by wertklop** [comment]
Still need to be relative system variable JAVA_HOME=<JDK 11>
