### ISSUE TITLE
Compiling fails on ubuntu 18.10

### ISSUE THREAD

**Issue by araspitzu** [gluonhq/client-samples#21]
### System Info
Host: ubuntu 18.10 on x86_64
JDK= OpenJDK 11.0.3
Maven: 3.6.0

### Problem
Trying to run the maven goal `client:compile` on the Maven/HelloWorld sample fails with 'Not enough memory':
```
andrea@andrea-tkp:~/workspace/client-samples/Maven/HelloWorld$ mvn clean client:compile
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ helloworld ---
[INFO] Deleting /home/andrea/workspace/client-samples/Maven/HelloWorld/target
[INFO] 
[INFO] --- client-maven-plugin:0.0.12:compile (default-cli) @ helloworld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/andrea/workspace/client-samples/Maven/HelloWorld/src/main/resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/andrea/workspace/client-samples/Maven/HelloWorld/target/classes
Omega :: host triplet = x86_64-linux-linux
Omega :: target triplet = x86_64-linux-linux
[Tue Aug 27 12:04:41 CEST 2019][INFO] [SUB] [helloWorld:15374]    classlist:   1,211.57 ms
[Tue Aug 27 12:04:42 CEST 2019][INFO] [SUB] [helloWorld:15374]        (cap):   1,002.13 ms
[Tue Aug 27 12:04:43 CEST 2019][INFO] [SUB] [helloWorld:15374]        setup:   2,569.50 ms
[Tue Aug 27 12:04:43 CEST 2019][INFO] [SUB] WARNING: An illegal reflective access operation has occurred
[Tue Aug 27 12:04:43 CEST 2019][INFO] [SUB] WARNING: Illegal reflective access by com.oracle.svm.util.ReflectionUtil (file:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/svm/builder/pointsto.jar) to method sun.nio.ch.IOUtil.initIDs()
[Tue Aug 27 12:04:43 CEST 2019][INFO] [SUB] WARNING: Please consider reporting this to the maintainers of com.oracle.svm.util.ReflectionUtil
[Tue Aug 27 12:04:43 CEST 2019][INFO] [SUB] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[Tue Aug 27 12:04:43 CEST 2019][INFO] [SUB] WARNING: All illegal access operations will be denied in a future release
[Tue Aug 27 12:05:09 CEST 2019][INFO] [SUB] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000569400000, 2550136832, 0) failed; error='Not enough space' (errno=12)
[Tue Aug 27 12:05:09 CEST 2019][INFO] [SUB] #
[Tue Aug 27 12:05:09 CEST 2019][INFO] [SUB] # There is insufficient memory for the Java Runtime Environment to continue.
[Tue Aug 27 12:05:09 CEST 2019][INFO] [SUB] # Native memory allocation (mmap) failed to map 2550136832 bytes for committing reserved memory.
[Tue Aug 27 12:05:09 CEST 2019][INFO] [SUB] # An error report file with more information is saved as:
[Tue Aug 27 12:05:09 CEST 2019][INFO] [SUB] # /home/andrea/workspace/client-samples/Maven/HelloWorld/target/client/linux-x86_64/gvm/hs_err_pid15374.log
Error compiling, compilation command was java -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:-UseJVMCICompiler -Dtruffle.TrustAllTruffleRuntimeProviders=true -Dsubstratevm.IgnoreGraalVersionCheck=true -Djava.lang.invoke.stringConcat=BC_SB -Xss10m -Xms1g -Xmx13441813704 -Duser.country=US -Duser.language=en -Dgraalvm.version=20.0.0-ea+15 -Dsvm.platform=org.graalvm.nativeimage.impl.InternalPlatform$LINUX_JNI_AMD64 -Dorg.graalvm.version=20.0.0-ea+15 -Dcom.oracle.graalvm.isaot=true --add-exports jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED --add-exports jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED --add-exports jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED --add-exports jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED --add-exports jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED --add-exports jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED --add-exports jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED --add-exports jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED --add-opens jdk.unsupported/sun.reflect=ALL-UNNAMED --add-opens java.base/jdk.internal.logger=ALL-UNNAMED --add-opens java.base/jdk.internal.module=ALL-UNNAMED --add-opens java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.lang.ref=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --module-path /home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/jvmci/graal-sdk.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/truffle/truffle-api.jar --upgrade-module-path /home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/jvmci/graal.jar -cp /home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/jvmci/graal-sdk.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/jvmci/graal.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/svm/builder/svm.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/svm/builder/objectfile.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/svm/builder/pointsto.jar com.oracle.svm.hosted.NativeImageGeneratorRunner -imagecp /home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/jvmci/graal-sdk.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/jvmci/graal.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/svm/builder/svm.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/svm/builder/objectfile.jar:/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/svm/builder/pointsto.jar:/home/andrea/workspace/client-samples/Maven/HelloWorld/target/classes: -H:CLibraryPath=/home/andrea/.gluon/omega/graalLibs/20.0.0-ea+15/bundle/lib/svm/clibraries/linux-amd64 -H:Class=hello.HelloWorld -H:+ReportExceptionStackTraces -H:ReflectionConfigurationFiles=/home/andrea/workspace/client-samples/Maven/HelloWorld/target/client/linux-x86_64/gvm/reflectionconfig-linux.json -H:JNIConfigurationFiles=/home/andrea/workspace/client-samples/Maven/HelloWorld/target/client/linux-x86_64/gvm/jniconfig-linux.json -H:TempDirectory=/home/andrea/workspace/client-samples/Maven/HelloWorld/target/client/linux-x86_64/gvm/tmp -H:IncludeResources=.*/.*frag$ -H:IncludeResources=.*/.*fxml$ -H:IncludeResources=.*/.*css$ -H:IncludeResources=.*/.*gls$ -H:IncludeResources=.*/.*ttf$ -H:IncludeResources=.*/.*png$ -H:IncludeResources=.*/.*jpg$ -H:IncludeResources=.*/.*jpeg$ -H:IncludeResources=.*/.*gif$ -H:IncludeResources=.*/.*bmp$ -H:IncludeResources=.*/.*license$ -H:IncludeResources=.*/.*json$ -H:IncludeResources=.*frag$ -H:IncludeResources=.*fxml$ -H:IncludeResources=.*css$ -H:IncludeResources=.*gls$ -H:IncludeResources=.*ttf$ -H:IncludeResources=.*png$ -H:IncludeResources=.*jpg$ -H:IncludeResources=.*jpeg$ -H:IncludeResources=.*gif$ -H:IncludeResources=.*bmp$ -H:IncludeResources=.*license$ -H:IncludeResources=.*json$ -H:Name=helloWorld -H:+ReportUnsupportedElementsAtRuntime -H:+AddAllCharsets -H:+AllowIncompleteClasspath -H:EnableURLProtocols=http,https
java.lang.RuntimeException: Error compiling
	at com.gluonhq.omega.SVMBridge.compile(SVMBridge.java:312)
	at com.gluonhq.omega.target.LinuxTargetProcess.compileApplication(LinuxTargetProcess.java:105)
	at com.gluonhq.omega.target.AbstractTargetProcess.compile(AbstractTargetProcess.java:328)
	at com.gluonhq.omega.Omega.nativeCompile(Omega.java:72)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:77)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.817 s
[INFO] Finished at: 2019-08-27T12:05:09+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.0.12:compile (default-cli) on project helloworld: Error: Error compiling -> [Help 1]
```

I tried adding `<runtimeArgsList> -Xmx2G </runtimeArgsList>` to the configuration section of `client-maven-plugin` but this was unsuccessful.

**Comment by jperedadnr** [comment]
The memory settings are set for native compilation internally. You can do a test, however, by editing the `/home/andrea/workspace/client-samples/Maven/HelloWorld/target/client/linux-x86_64/gvm/compile.sh` file and increase the default memory settings:
```
-Xss10m \
-Xms1g \
-Xmx13441813704 \
```
Then you can run `compile.sh` and see if that ends successfully. If it does, you could run the `client:link` and `client:run` goals.
In any case, let us know how it goes.

**Comment by araspitzu** [comment]
Thanks for the answer increasing the available memory editing `compile.sh` fixed the issue, however i can't run `mvn clean client:build` because the `clean` goal wipes the custom `compile.sh` so i have to break down the building steps (first try to compile, then edit and re-execute the build step).

**Comment by jperedadnr** [comment]
Thanks for testing. What memory settings did you change? Can you also mention your hardware specs?

The issuee has to be fixed internally in the Omega dependency. 

Until then, you will have to break your build into these steps:
- mvn clean client:compile (wait until it fails)
- edit compile.sh, add more memory, run compile.sh
- mvn client:link
- mvn client:run

**Comment by araspitzu** [comment]
Okay, i only replaced the `-Xmx13441813704` with `-Xmx2g`. Hardware specs are:
- 16 GB memory
- 500 GB hard disk
- CPU: i7-8550U

**Comment by jperedadnr** [comment]
@araspitzu Is it possible that you can test the latest version of the Client maven plugin? The new release has deep underlying changes.

**Comment by araspitzu** [comment]
Build done successfully using client-samples @ 55ee70e8 and latest graalVM (19.3.0) :tada:
