### ISSUE TITLE
HelloWorld: Linking fails (Fedora 31)  /usr/bin/ld: cannot find -lstdc++

### ISSUE THREAD

**Issue by taranion** [gluonhq/client-samples#38]
Hi,

Trying the HelloWorld example on Fedora Linux 31. 
It compiles fine, but linking fails because it won't find the libstdc++

```
Linking failed. Details from linking below:
Command was: gcc /tmp/client-samples/Maven/HelloWorld/target/client/x86_64-linux/gvm/helloWorld/launcher.o /tmp/client-samples/Maven/HelloWorld/target/client/x86_64-linux/gvm/tmp/SVM-1576524751781/hello.helloworld.o -ljava -lnio -lzip -lnet -ljvm -lstrictmath -lz -ldl -lj2pkcs11 -lsunec -lextnet -lstdc++ -rdynamic -llibchelper -lpthread -o /tmp/client-samples/Maven/HelloWorld/target/client/x86_64-linux/helloWorld -L/opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64 -L/home/prelle/.gluon/substrate/javaStaticSdk/14-ea+5/linux-x86_64/labs-staticjdk/lib/static
/usr/bin/ld: cannot find -lstdc++
collect2: Fehler: ld gab 1 als Ende-Status zurück
java.lang.RuntimeException: Linking failed
	at com.gluonhq.NativeLinkMojo.execute(NativeLinkMojo.java:55)
```

There is indeed no static libstdc++.a in either  /opt/graalvm-ce-java11-19.3.0  or /home/prelle/.gluon/substrate/... 

This is likely  not an issue of the examples itself, but perhaps  you could point me where to go from here.

(Funny enough, the Maven run finishes reporting a "Success")
```
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.7:link (default-cli) on project helloworld: Error: Linking failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

```

**Comment by taranion** [comment]
Okay, solved it myself by simply installing the missing library from Fedora
  yum install libstdc++-static

You might want to add that information somewhere in your documentation. 
Sorry for bothering you.
