### ISSUE TITLE
Build error on Windows 10 : Missing a reflection configuration

### ISSUE THREAD

**Issue by azman6r6m1** [gluonhq/client-samples#41]
Hi,

I failed to build HelloFX project in windows. Where can I find reflection configuration file named reflectionconfig-javafx-x86_64-windows.json?

```
D:\ws\git\HelloFX>set GRAALVM_HOME=%GRAALVM11_HOME%

D:\ws\git\HelloFX>set JAVA_HOME=%GRAALVM_HOME%

D:\ws\git\HelloFX>set PATH=%GRAALVM_HOME%\bin;%PATH%

D:\ws\git\HelloFX>vcvarsall x86_amd64
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.2
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'

D:\ws\git\HelloFX>mvn clean client:build
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hellofx ---
[INFO] Deleting D:\ws\git\HelloFX\target
[INFO]
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.10:build (default-cli) @ hellofx ---
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.10:compile (default-cli) @ hellofx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to D:\ws\git\HelloFX\target\classes
We will now compile your code for x86_64-microsoft-windows. This may take some time.
java.io.IOException: Missing a reflection configuration file named reflectionconfig-javafx-x86_64-windows.json
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.createReflectionConfig(AbstractTargetConfiguration.java:478)
[INFO] ------------------------------------------------------------------------
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.compile(AbstractTargetConfiguration.java:142)
[INFO] BUILD FAILURE
        at com.gluonhq.substrate.SubstrateDispatcher.nativeCompile(SubstrateDispatcher.java:197)
[INFO] ------------------------------------------------------------------------
        at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:69)
[INFO] Total time:  4.648 s
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[INFO] Finished at: 2020-01-07T13:42:07+08:00
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[INFO] ------------------------------------------------------------------------
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.10:compile (default-cli) on project hellofx: Error: Missing a reflection configuration file named reflectionconfig-javafx-x86_64-windows.json -> [Help 1]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] For more information about the errors and possible solutions, please read the following articles:
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.979 s
[INFO] Finished at: 2020-01-07T13:42:07+08:00
[INFO] ------------------------------------------------------------------------

D:\ws\git\HelloFX>
```

**Comment by warmuuh** [comment]
issue in substrate: https://github.com/gluonhq/substrate/issues/205
