### ISSUE TITLE
Compilation Fails on Pop! OS 19.10 (based on Ubuntu)

### ISSUE THREAD

**Issue by dubbadhar** [gluonhq/client-samples#43]
I opened the `HelloFX` Maven Project on IntelliJ IDEA, and when running `mvn clean client:build`, compilation fails and i get this output :

```
dubbadhar@pop-os:~/Downloads/client-samples-master/Maven/HelloFX$ mvn clean client:build
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hellofx ---
[INFO] Deleting /home/dubbadhar/Downloads/client-samples-master/Maven/HelloFX/target
[INFO] 
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.11:build (default-cli) @ hellofx ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< hello:hellofx >----------------------------
[INFO] Building hellofx 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.11:compile (default-cli) @ hellofx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/dubbadhar/Downloads/client-samples-master/Maven/HelloFX/target/classes
We will now compile your code for x86_64-linux-linux. This may take some time.
Shutdown Server(pid: 8296, port: 45455)
Build on Server(pid: 10957, port: 37815)*
[hellofx.hellofx:10957]    classlist:   4,395.78 ms
[hellofx.hellofx:10957]        (cap):   1,614.19 ms
[hellofx.hellofx:10957]        setup:   3,778.55 ms
Error: Error parsing reflection configuration in /home/dubbadhar/Downloads/client-samples-master/Maven/HelloFX/target/client/x86_64-linux/gvm/reflectionconfig-x86_64-linux.json:
Method com.sun.javafx.logging.PrintLogger.createInstance() not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Compilation failed with result = 1
Compilation failed. See error printed above.
[INFO] 
[INFO] --- client-maven-plugin:0.1.11:link (default-cli) @ hellofx ---
java.lang.IllegalArgumentException: Linking failed, since there is no objectfile named hellofx.hellofx.o under /home/dubbadhar/Downloads/client-samples-master/Maven/HelloFX/target/client/x86_64-linux/gvm
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.lambda$link$0(AbstractTargetConfiguration.java:205)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.link(AbstractTargetConfiguration.java:203)
        at com.gluonhq.substrate.target.LinuxTargetConfiguration.link(LinuxTargetConfiguration.java:79)
        at com.gluonhq.substrate.SubstrateDispatcher.nativeLink(SubstrateDispatcher.java:213)
        at com.gluonhq.NativeLinkMojo.execute(NativeLinkMojo.java:54)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[INFO] ------------------------------------------------------------------------
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[INFO] Total time:  12.491 s
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[INFO] Finished at: 2020-01-15T15:29:15+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.11:link (default-cli) on project hellofx: Error: Linking failed, since there is no objectfile named hellofx.hellofx.o under /home/dubbadhar/Downloads/client-samples-master/Maven/HelloFX/target/client/x86_64-linux/gvm -> [Help 1]
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.749 s
[INFO] Finished at: 2020-01-15T15:29:15+05:30
[INFO] ------------------------------------------------------------------------
```

**Comment by jperedadnr** [comment]
It looks like you are running with JavaFX 11. Can you try with 12 or 13?

**Comment by dubbadhar** [comment]
I installed the missing libraries but then still it could not link. Since this is already a bug, I'm closing this.

**Comment by jperedadnr** [comment]
Feel free to open a new bug if the problem linking persists. If you have installed all the required libraries, what is the issue?

**Comment by dubbadhar** [comment]
No issues, after rebooting i was able to build and link it as well. However, JavaFX Media does not work. No errors thrown, nothing. will open a new issue for that

**Comment by jperedadnr** [comment]
Related: https://github.com/gluonhq/client-maven-plugin/issues/28

But yes, a better message should be shown when using Media or Web...
