### ISSUE TITLE
HelloWorld for iOS build failed

### ISSUE THREAD

**Issue by Gamadril** [gluonhq/client-samples#55]
I've tried to build the HelloWorld sample for iOS, but without success. Can you tell me what's wrong?

```
buser@buser-mbp HelloWorld % mvn clean client:build
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ helloworld ---
[INFO] Deleting /Users/buser/Projects/client-samples/Maven/HelloWorld/target
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.15:build (default-cli) @ helloworld ---
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.15:compile (default-cli) @ helloworld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/buser/Projects/client-samples/Maven/HelloWorld/src/main/resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/buser/Projects/client-samples/Maven/HelloWorld/target/classes
We will now compile your code for arm64-apple-ios. This may take some time.
Build on Server(pid: 34820, port: 59060)*
[hello.helloworld:34820]    classlist:   2,812.96 ms,  1.00 GB
[hello.helloworld:34820]        (cap):   1,608.48 ms,  1.33 GB
[hello.helloworld:34820]        setup:   3,905.08 ms,  1.33 GB
[hello.helloworld:34820]   (typeflow):  24,287.44 ms,  3.55 GB
[hello.helloworld:34820]    (objects):  24,719.93 ms,  3.55 GB
[hello.helloworld:34820]   (features):   2,313.20 ms,  3.55 GB
[hello.helloworld:34820]     analysis:  52,893.52 ms,  3.55 GB
[hello.helloworld:34820]     (clinit):     747.79 ms,  4.17 GB
[hello.helloworld:34820]     universe:   3,607.49 ms,  4.17 GB
[hello.helloworld:34820]      (parse):   7,517.33 ms,  4.17 GB
[hello.helloworld:34820]     (inline):   5,327.66 ms,  4.84 GB
Error: Image build request failed with exit status -1
Compilation failed with result = 255
Compilation failed. See error printed above.
[INFO] 
[INFO] --- client-maven-plugin:0.1.15:link (default-cli) @ helloworld ---
java.lang.IllegalArgumentException: Linking failed, since there is no objectfile named hello.helloworld.o under /Users/buser/Projects/client-samples/Maven/HelloWorld/target/client/arm64-ios/gvm
	at com.gluonhq.substrate.target.AbstractTargetConfiguration.lambda$link$0(AbstractTargetConfiguration.java:210)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.gluonhq.substrate.target.AbstractTargetConfiguration.link(AbstractTargetConfiguration.java:208)
	at com.gluonhq.substrate.target.IosTargetConfiguration.link(IosTargetConfiguration.java:148)
	at com.gluonhq.substrate.SubstrateDispatcher.nativeLink(SubstrateDispatcher.java:216)
	at com.gluonhq.NativeLinkMojo.execute(NativeLinkMojo.java:54)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:22 min
[INFO] Finished at: 2020-02-21T09:13:49+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.15:link (default-cli) on project helloworld: Error: Linking failed, since there is no objectfile named hello.helloworld.o under /Users/buser/Projects/client-samples/Maven/HelloWorld/target/client/arm64-ios/gvm -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:25 min
[INFO] Finished at: 2020-02-21T09:13:49+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.15:build (default-cli) on project helloworld: Error, client:build failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by jperedadnr** [comment]
The error isn't clear, but from experience that looks like there was a running process that prevented this new one from succeeding. 

You can try to kill first all existing java processes, and try again?

**Comment by Gamadril** [comment]
sadly it doesn't help

**Comment by jperedadnr** [comment]
Open Task Monitor app, see that you don't have any long running process from Java, LLVM, LLC, Gradle or related to this. If you have it, kill it. Then run again, from command line.

**Comment by Gamadril** [comment]
none of the processes are running when starting maven build

**Comment by jperedadnr** [comment]
Post your machine specs, and which are the JDK and GraalVM versions?

**Comment by Gamadril** [comment]
MacOS Catalina 10.15.3
```
 mvn -version                                                                              
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/local/share/java/maven3
Java version: 11.0.5, vendor: Oracle Corporation, runtime: /Users/dwi/Projects/MKP/graalvm/graalvm-svm-darwin-20.0.0-ea+21
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
```

Version is from the README:
GraalVM: https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-darwin-20.0.0-ea+21.zip
JDK: JAVA_HOME = $GRAALVM_HOME
```
 java -version 
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
OpenJDK 64-Bit Server VM GraalVM 20.0.0-dev (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)
```

**Comment by jperedadnr** [comment]
Missing your Mac details (RAM mainly). The process is quite intensive in memory.

**Comment by Gamadril** [comment]
```
Model Name:	MacBook Pro
...
  Processor Name:	Dual-Core Intel Core i7
  Processor Speed:	3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
...
```
No VMs running in VMWare.

**Comment by jperedadnr** [comment]
That is more or less my setup. 
Does it work when you target desktop? Have you installed LLVM as documented https://github.com/gluonhq/client-samples#requirements-1? (we'll have a new build that will remove the need of that).

**Comment by Gamadril** [comment]
llvm from http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz is installed and in PATH.
```
which clang                                                                               
/Users/buser/Projects/clang+llvm-6.0.0-x86_64-apple-darwin/bin/clang
```

**Comment by jperedadnr** [comment]
Can you test the latest Client plugin 0.1.18, with the new GraalVM build:
https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-darwin-20.1.0-ea+26.zip
and report back?
Note that LLVM is not needed anymore (remove it from your PATH).

**Comment by seniorglez** [comment]
I'm having the same problem here are all the stuff you asked for and the result of the build
```
diego@Diegos-MacBook-Pro HelloFXML % mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /opt/graalvm-svm-darwin-20.1.0-ea+28
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
```
![Screenshot 2020-05-01 at 19 31 29](https://user-images.githubusercontent.com/44611837/80826379-65805380-8be2-11ea-83e4-dc991a0bdc59.png)

I can compile and run the example on desktop in less than a minute, but then when I type the mvn client:run command it close before it shows anything on the screen.

```
diego@Diegos-MacBook-Pro HelloWorld % mvn client:run
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.23:run (default-cli) @ helloworld ---
[Fri May 01 19:40:10 CEST 2020][INFO] ==================== RUN TASK ====================
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.898 s
[INFO] Finished at: 2020-05-01T19:40:10+02:00
[INFO] ------------------------------------------------------------------------
```

For some reason I can run the HelloFXML example and it works property. Anyway I can't compile to IOS both of them. Here is the output for HelloWorld.
```
diego@Diegos-MacBook-Pro HelloWorld % mvn clean client:build -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ helloworld ---
[INFO] Deleting /Users/diego/Desktop/client-samples/Maven/HelloWorld/target
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.23:build (default-cli) @ helloworld ---
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> client-maven-plugin:0.1.23:compile (default-cli) > process-classes @ helloworld >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ helloworld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/diego/Desktop/client-samples/Maven/HelloWorld/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ helloworld ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/diego/Desktop/client-samples/Maven/HelloWorld/target/classes
[INFO] 
[INFO] <<< client-maven-plugin:0.1.23:compile (default-cli) < process-classes @ helloworld <<<
[INFO] 
[INFO] 
[INFO] --- client-maven-plugin:0.1.23:compile (default-cli) @ helloworld ---
[Fri May 01 19:54:37 CEST 2020][INFO] ==================== COMPILE TASK ====================
[Fri May 01 19:54:37 CEST 2020][INFO] We will now compile your code for arm64-apple-ios. This may take some time.
[Fri May 01 19:54:37 CEST 2020][SEVERE] Process sdk failed with result: 1
Check the log files under /Users/diego/Desktop/client-samples/Maven/HelloWorld/target/client/arm64-ios/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[Fri May 01 19:54:37 CEST 2020][INFO] Logging process [sdk] to file: /Users/diego/Desktop/client-samples/Maven/HelloWorld/target/client/log/process-sdk-1588355677337.log
java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1090)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.gluonhq.substrate.util.ProcessRunner.setupProcess(ProcessRunner.java:315)
	at com.gluonhq.substrate.util.ProcessRunner.runProcess(ProcessRunner.java:179)
	at com.gluonhq.substrate.target.AbstractTargetConfiguration.compileAdditionalSources(AbstractTargetConfiguration.java:329)
	at com.gluonhq.substrate.target.AbstractTargetConfiguration.compile(AbstractTargetConfiguration.java:129)
	at com.gluonhq.substrate.SubstrateDispatcher.nativeCompile(SubstrateDispatcher.java:343)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:54)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.629 s
[INFO] Finished at: 2020-05-01T19:54:37+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.23:compile (default-cli) on project helloworld: Error: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.318 s
[INFO] Finished at: 2020-05-01T19:54:37+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.23:build (default-cli) on project helloworld: Error, client:build failed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.gluonhq:client-maven-plugin:0.1.23:build (default-cli) on project helloworld: Error, client:build failed
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error, client:build failed
    at com.gluonhq.NativeBuildMojo.execute (NativeBuildMojo.java:75)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
I you need more information about my machine just let me know.
