### ISSUE TITLE
iOS applications are rejected from the App Store

### ISSUE THREAD

**Issue by stevesoltys** [gluonhq/client-samples#58]
Same issue as https://github.com/oracle/graal/issues/1568, but I figured I'd request it here in hopes that we could have the hotfix in the Gluon version of GraalVM in the meantime.

For reference, I am using this verision of GraalVM: https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-darwin-20.1.0-ea+25.zip

**Comment by jperedadnr** [comment]
Using that exact same version(20.1.0-ea+25) there are apps published in the App Store. What message do you get from Apple?

**Comment by johanvos** [comment]
Next release has that hotfix. Should be there hopefully tomorrow.

**Comment by stevesoltys** [comment]
Thank you!

**Comment by jperedadnr** [comment]
@stevesoltys Can you test 
https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-darwin-20.1.0-ea+26.zip
and report back?

**Comment by stevesoltys** [comment]
With the new release I am receiving a new (and almost certainly unrelated) issue during the native image build.

```
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] Fatal error:java.lang.NumberFormatException
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:358)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:517)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:116)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:544)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] Caused by: java.lang.NumberFormatException: null
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.lang.Integer.parseInt(Integer.java:614)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.query.QueryResultParser.parseIntegerProperty(QueryResultParser.java:232)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructFieldInfo(QueryResultParser.java:144)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.StructFieldInfo.accept(StructFieldInfo.java:74)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructInfo(QueryResultParser.java:134)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.StructInfo.accept(StructInfo.java:62)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.visitNativeCodeInfo(InfoTreeVisitor.java:36)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.query.QueryResultParser.parse(QueryResultParser.java:78)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.CAnnotationProcessorCache.get(CAnnotationProcessorCache.java:114)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:82)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:389)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1538)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1034)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Sat Mar 21 21:56:21 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

It may have something to do with the extra native libraries I have included in the build, but I'm not sure.

However, if https://github.com/johanvos/graal/commit/2436b48a10a87e49ef739da594595e72a0d44993  or similar was applied to that build, then you can mark this issue as resolved.

I applied that patch to the previous release and can confirm that if `_CFCopyServerVersionDictionary` and `_CFCopySystemVersionDictionary` are no longer being called, the application will be accepted in the App Store.

**Comment by stevesoltys** [comment]
Apologies, my personal substrate and maven-client-plugin forks were not up to date.

Can confirm that the new build is working, thank you! :)
