### ISSUE TITLE
nativeCompile setup steps fails for Android (with suggested Graal distribution)

### ISSUE THREAD

**Issue by jskov** [gluonhq/client-samples#67]
When I try to build HelloFX sample using the suggested [Graal distribution](https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-20.1.0-ea+26.zip) I get this result:

````> Task :nativeCompile                                                                                                                        
[Wed Apr 01 09:39:34 CEST 2020][INFO] ==================== COMPILE TASK ====================                                   
[Wed Apr 01 09:39:34 CEST 2020][INFO] We will now compile your code for aarch64-linux-android. This may take some time.
                                                                                                                                             
[Wed Apr 01 09:39:38 CEST 2020][INFO] [SUB] [hellofx.hellofx:95406]    classlist:   2,717.41 ms,  0.96 GB                                   
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB] [hellofx.hellofx:95406]        (cap):     206.54 ms,  0.96 GB                                   
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB] [hellofx.hellofx:95406]        setup:     732.43 ms,  0.96 GB         
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB] Fatal error:java.lang.NumberFormatException                                                                                                                                                                                                   
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                                                                                               
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)          
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:358)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:517)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:116) 
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:544)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB] Caused by: java.lang.NumberFormatException: null                                                                                                                                                                                              
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.lang.Integer.parseInt(Integer.java:614)         
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.lang.Integer.parseInt(Integer.java:770)    
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.query.QueryResultParser.parseIntegerProperty(QueryResultParser.java:232)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructFieldInfo(QueryResultParser.java:144)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.info.StructFieldInfo.accept(StructFieldInfo.java:74)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructInfo(QueryResultParser.java:134)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.info.StructInfo.accept(StructInfo.java:62)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.info.InfoTreeVisitor.visitNativeCodeInfo(InfoTreeVisitor.java:36)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.query.QueryResultParser.parse(QueryResultParser.java:78)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.CAnnotationProcessorCache.get(CAnnotationProcessorCache.java:114)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:82)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:389)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1538)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1034)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863) 
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) 
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[Wed Apr 01 09:39:39 CEST 2020][INFO] [SUB] Error: Image build request failed with exit status 1

> Task :nativeCompile
[Wed Apr 01 09:39:39 CEST 2020][SEVERE] Process compile failed with result: 1
Check the log files under /opt/sources/eclipse.git/client-samples/Gradle/HelloFX/build/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[Wed Apr 01 09:39:39 CEST 2020][INFO] Logging process [compile] to file: /opt/sources/eclipse.git/client-samples/Gradle/HelloFX/target/client/log/process-compile-1585726779098.log
[Wed Apr 01 09:39:39 CEST 2020][SEVERE] Compiling failed.
Check the log files under /opt/sources/eclipse.git/client-samples/Gradle/HelloFX/build/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.

> Task :nativeCompile FAILED
````
Using the official CE 20.0.0 distribution of Graal gets past this point.

**Comment by tiainen** [comment]
Could you give it another try with version 27? https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-20.1.0-ea+27.zip

**Comment by jskov** [comment]
That works better, @tiainen, thank you!
It compiles and builds without problems.
