### ISSUE TITLE
Missing Android NDK Ubuntu 19.10 Maven graalvm-svm-linux-20.1.0-ea+27

### ISSUE THREAD

**Issue by bezvaapp** [gluonhq/client-samples#71]
When I am building the sample HelloGluon for Android target, the maven displays that it downloaded both Android tools and and ndk successfully but then it displays the error below. The directory 
`/home/anonymous/.gluon/substrate/Android/`
contains only the tools directory, no ndk-bundle.

I downloaded the NDK from the Android site and put it manually into the directory. Then the build continues but fails later with:
`Error: Image build request failed with exit status 137` 

Probably the NDK version I downloaded is not correct.

Do you have any workaround please? Thank you.

```
[Tue Apr 14 14:38:36 CEST 2020][INFO] We will now compile your code for aarch64-linux-android. This may take some time.
java.io.IOException: You specified an android ndk, but it doesn't contain /home/anonymous/.gluon/substrate/Android/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/ldlld
	at com.gluonhq.substrate.target.AndroidTargetConfiguration.compile(AndroidTargetConfiguration.java:130)
	at com.gluonhq.substrate.SubstrateDispatcher.nativeCompile(SubstrateDispatcher.java:343)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:54)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by jperedadnr** [comment]
Can you try with plugin version 0.1.21-SNAPSHOT ?
You will need to add the repository:
```
<pluginRepositories>
        <pluginRepository>
            <id>gluon-releases</id>
            <url>https://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
        </pluginRepository>
        <pluginRepository>
            <id>snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by bezvaapp** [comment]
Thank you for a quick reply. I tried it with the maven plugin snapshot. Now the Android NDK and platforms are downloaded by the plugin. Unfortunately the build fails later with status 137. The log does not contain additional error message.

```
INFO: Downloading Android NDK and toolchain. It may take several minutes depending on your bandwidth.
......................................................................................................................................................
Apr 14, 2020 4:32:19 PM com.gluonhq.substrate.util.Logger logInfo
INFO: Android NDK and toolchain downloaded successfully
[Tue Apr 14 16:32:19 CEST 2020][INFO] ==================== COMPILE TASK ====================
[Tue Apr 14 16:32:19 CEST 2020][INFO] We will now compile your code for aarch64-linux-android. This may take some time.
[Tue Apr 14 16:32:27 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]    classlist:   6,571.39 ms,  0.96 GB
[Tue Apr 14 16:32:29 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]        (cap):     416.39 ms,  0.96 GB
[Tue Apr 14 16:32:31 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]        setup:   3,151.04 ms,  0.96 GB
[Tue Apr 14 16:34:35 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]     (clinit):   1,757.95 ms,  3.48 GB
[Tue Apr 14 16:34:37 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]   (typeflow):  57,774.97 ms,  3.48 GB
[Tue Apr 14 16:34:37 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]    (objects):  53,704.34 ms,  3.48 GB
[Tue Apr 14 16:34:37 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]   (features):   8,817.07 ms,  3.48 GB
[Tue Apr 14 16:34:37 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]     analysis: 125,982.91 ms,  3.48 GB
[Tue Apr 14 16:34:40 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]     universe:   3,068.72 ms,  3.48 GB
[Tue Apr 14 16:35:00 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]      (parse):  19,077.66 ms,  3.29 GB
[Tue Apr 14 16:35:23 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]     (inline):  23,277.95 ms,  3.38 GB
[Tue Apr 14 16:37:09 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]    (compile): 105,511.71 ms,  3.32 GB
[Tue Apr 14 16:37:10 CEST 2020][INFO] [SUB] [com.gluonhq.hello.hellogluon:7208]    (bitcode):   1,230.34 ms,  3.32 GB
[Tue Apr 14 16:44:40 CEST 2020][INFO] [SUB] Error: Image build request failed with exit status 137
[Tue Apr 14 16:44:41 CEST 2020][SEVERE] Process compile failed with result: 137
Check the log files under /home/anonymous/eclipse-workspace/HelloGluon/target/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[Tue Apr 14 16:44:41 CEST 2020][INFO] Logging process [compile] to file: /home/anonymous/eclipse-workspace/HelloGluon/target/client/log/process-compile-1586875481073.log
[Tue Apr 14 16:44:41 CEST 2020][SEVERE] Compiling failed.
Check the log files under /home/anonymous/eclipse-workspace/HelloGluon/target/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by jperedadnr** [comment]
137 means low memory. The process is quite memory intensive. 
It should run fine with 16 GB RAM, and extra swap memory up until 8 GB. With lower memory you will have to close all other applications while compiling, and even might be not enough.

**Comment by bezvaapp** [comment]
Thank you for the advice. I have a computer with 16 GiB but the Ubuntu is running in VirtualBox because I have Windows 10. I increased the VM RAM to 10 GiB and swapfile to 8 GiB and in the end it compiled successfully.

**Comment by jperedadnr** [comment]
Ok, good to know. Feel free to close this issue

**Comment by bezvaapp** [comment]
Fixed.
