### ISSUE TITLE
Unable to run examples from IntelliJ IDEA

### ISSUE THREAD

**Issue by wimdeblauwe** [gluonhq/client-samples#9]
I am testing with the Maven HelloFX sample. I can run the sample on the command line using `mvn javafx:run`. However, when I try to run from IntelliJ IDEA, I get:

```
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.scene.control.ControlHelper (in unnamed module @0xabf121a) cannot access class com.sun.javafx.scene.layout.RegionHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.layout to unnamed module @0xabf121a
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javafx.scene.control.Control.<clinit>(Control.java:86)
	at hellofx.HelloFX.start(HelloFX.java:18)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Exception running application hellofx.HelloFX
```
In both cases, I am using OpenJDK 11.0.2. I saw https://stackoverflow.com/questions/53600855/invocationtargetexception-when-trying-to-run-a-javafx-program but not sure if it is related, and it is also not clear what the solution is there.

**Comment by jperedadnr** [comment]
This is a known issue, when running a Maven project with JavaFX 11+, IntelliJ will use a default configuration that won't work (i.e., it doesn't add the required `javafx.controls` module). 

It is pretty much the same as this question: https://stackoverflow.com/questions/54291958/javafx-11-illegalaccesserror-when-creating-label/, though it is not related to Maven.

If you want to run from IntelliJ, you have to edit the Run configuration and add something like: `mvn clean javafx:run`, as explained in https://openjfx.io/openjfx-docs/#IDE-Intellij, Maven sections.

**Comment by wimdeblauwe** [comment]
It is possible to run from IntelliJ using JavaFX 12 and Java 11: I just needed to add a `module-info.java` file at `src/main/java` with this contents:

```
module hellofx {
    requires javafx.controls;

    opens hellofx to javafx.graphics;
}
```

After that I could just run from IntelliJ as any other application. The same also works with Java 12.

**Comment by jperedadnr** [comment]
Sure, as soon as you add module-info, IntelliJ manages to resolve the module-path. But the idea of having a plugin and maven goals is to use them. The plugin will work for modular and non-modular projects.
