### ISSUE TITLE
Ubuntu Build fail. (error=2, No such file or directory) 

### ISSUE THREAD

**Issue by KopeMorta** [gluonhq/client-samples#91]
When i try build any project from this repository i got same error every time:

```
[Tue Jun 23 21:24:53 EEST 2020][INFO] We will now compile your code for x86_64-linux-linux. This may take some time.
java.io.IOException: Cannot run program "jar": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.gluonhq.substrate.util.ProcessRunner.setupProcess(ProcessRunner.java:336)
	at com.gluonhq.substrate.util.ProcessRunner.runProcess(ProcessRunner.java:194)
	at com.gluonhq.substrate.util.ProcessRunner.runProcess(ProcessRunner.java:180)
	at com.gluonhq.substrate.model.ClassPath.getJars(ClassPath.java:125)
	at com.gluonhq.substrate.config.ConfigResolver.<init>(ConfigResolver.java:77)
	at com.gluonhq.substrate.target.AbstractTargetConfiguration.getConfigurationFileArgs(AbstractTargetConfiguration.java:476)
	at com.gluonhq.substrate.target.AbstractTargetConfiguration.compile(AbstractTargetConfiguration.java:150)
	at com.gluonhq.substrate.target.LinuxTargetConfiguration.compile(LinuxTargetConfiguration.java:90)
	at com.gluonhq.substrate.SubstrateDispatcher.nativeCompile(SubstrateDispatcher.java:414)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:54)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 33 more
```

I install graalvm - (GraalVM CE 20.2.0-dev-20200620_0159)
Try with maven from IDE and installed maven, result the same.
My system is Kubuntu 20.04 LTS.

**Comment by jperedadnr** [comment]
`Cannot run program "jar"` means that `jar` is not in the path. Did you set `export JAVA_HOME=$GRAALVM_HOME`? Do you have an older JDK in the path?

**Comment by KopeMorta** [comment]
> `Cannot run program "jar"` means that `jar` is not in the path. Did you set `export JAVA_HOME=$GRAALVM_HOME`? Do you have an older JDK in the path?

Tried set graalvm_home with "export" and in pom in client-maven-plugin with graalvmHome. Same error.
Without graalvmHome have  other error:
```
org.apache.maven.plugin.MojoExecutionException: GraalVM installation directory not found. Either set GRAALVM_HOME as an environment variable or set graalvmHome in client-plugin configuration
	at com.gluonhq.NativeBaseMojo.createSubstrateDispatcher(NativeBaseMojo.java:131)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:53)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by jperedadnr** [comment]
You need to set both `GRAALVM_HOME` (or `graalvmHome`) _and_ `JAVA_HOME`. Note that `jar` should be found under `$JAVA_HOME/bin/jar`. 
Optionally, you can add JAVA_HOME to your `PATH`.

**Comment by KopeMorta** [comment]
> You need to set both `GRAALVM_HOME` (or `graalvmHome`) _and_ `JAVA_HOME`. Note that `jar` should be found under `$JAVA_HOME/bin/jar`.
> Optionally, you can add `JAVA_HOME/bin` to your `PATH`.

Yes, of course, I added both.

Adding a direct path to the PATH helped me.
Thanks for the help !

But it very strange how I could confuse the path many times in a row.

**Comment by tiainen** [comment]
I stumble upon this too from time to time and it is indeed very confusing. It would help if we just used `jar` that is provided in either `GRAALVM_HOME/bin` or `JAVA_HOME/bin`?

**Comment by jperedadnr** [comment]
Fixed with https://github.com/gluonhq/substrate/pull/690
