### ISSUE TITLE
Compilation failed for iOS: NumberFormatException

### ISSUE THREAD

**Issue by tausiq** [gluonhq/client-samples#99]
Hi! I tried to compile and run for macOS and it worked. Tried same for iOS and compilation failed. I installed `libusbmuxd` and `libimobiledevice` to run for iOS, but looks like it didn't get to that point and failed on compilation.

```
[Sat. Jul. 25 12:57:45 EDT 2020][INFO] ==================== COMPILE TASK ====================
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate



[Sat. Jul. 25 12:57:46 EDT 2020][INFO] We will now compile your code for arm64-apple-ios. This may take some time.
[Sat. Jul. 25 12:57:52 EDT 2020][INFO] [SUB] [hellofx.hellofx:54101]    classlist:   3,422.70 ms,  0.96 GB
[Sat. Jul. 25 12:57:52 EDT 2020][INFO] [SUB] WARNING: Using an older version of the labsjdk-11.
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] [hellofx.hellofx:54101]        (cap):     255.13 ms,  0.96 GB
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] [hellofx.hellofx:54101]        setup:   1,094.25 ms,  0.96 GB
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] Fatal error:java.lang.NumberFormatException
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:480)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:540)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] Caused by: java.lang.NumberFormatException: null
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.lang.Integer.parseInt(Integer.java:614)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.query.QueryResultParser.parseIntegerProperty(QueryResultParser.java:232)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructFieldInfo(QueryResultParser.java:144)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.StructFieldInfo.accept(StructFieldInfo.java:74)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructInfo(QueryResultParser.java:134)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.StructInfo.accept(StructInfo.java:62)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.visitNativeCodeInfo(InfoTreeVisitor.java:36)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.query.QueryResultParser.parse(QueryResultParser.java:78)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.CAnnotationProcessorCache.get(CAnnotationProcessorCache.java:114)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:84)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:526)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1539)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1036)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:868)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:553)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Sat. Jul. 25 12:57:53 EDT 2020][INFO] [SUB] Error: Image build request failed with exit status 1
[Sat. Jul. 25 12:57:53 EDT 2020][SEVERE] Process compile failed with result: 1
Check the log files under .../client-samples/Maven/HelloFX/target/client/arm64-ios/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
```

**Comment by jperedadnr** [comment]
Make sure you use a more recent GraalVM build, from https://github.com/graalvm/graalvm-ce-dev-builds/releases. 
Try for instance https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/20.3.0-dev-20200725_0200/graalvm-ce-java11-darwin-amd64-20.3.0-dev.tar.gz

It can be convenient to use the latest Client snapshot, so use in your pom:
```
    <client.plugin.version>0.1.29-SNAPSHOT</client.plugin.version>
...
   <pluginRepositories>
        <pluginRepository>
            <id>snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by tausiq** [comment]
I am already using `graalvm-ce-java11-20.3.0-dev`. Using `0.1.29-SNAPSHOT` worked! Thanks!
